FROM confluentinc/cp-server-connect-base:7.3.1

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest \
    && confluent-hub install --no-prompt confluentinc/kafka-connect-http:latest