# --- DEPLOYMENT DEL PRODUCER ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-direct-message-tcp-smf-nodejs
  namespace: solace
  labels:
    app: producer-direct-message-tcp-smf-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-direct-message-tcp-smf-nodejs
  template:
    metadata:
      labels:
        app: producer-direct-message-tcp-smf-nodejs
    spec:
      containers:
      - name: producer
        image: producer-direct-message-tcp-smf-nodejs:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SOLACE_URL
            value: "tcp://solace.solace.svc.cluster.local:55555"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# --- DEPLOYMENT DEL CONSUMER ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-direct-message-tcp-smf-nodejs
  namespace: solace
  labels:
    app: consumer-direct-message-tcp-smf-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-direct-message-tcp-smf-nodejs
  template:
    metadata:
      labels:
        app: consumer-direct-message-tcp-smf-nodejs
    spec:
      containers:
      - name: consumer
        image: consumer-direct-message-tcp-smf-nodejs:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SOLACE_URL
            value: "tcp://solace.solace.svc.cluster.local:55555"
        ports:
        - containerPort: 8081 # Cambiado para evitar confusiones, aunque al ser pods distintos podrían repetir
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"