FROM node:20-alpine

WORKDIR /app

# Copiamos los package desde la raíz (contexto actual)
COPY package*.json ./
RUN npm install

# Copiamos TODO el contenido del contexto
COPY . .

# AJUSTE AQUÍ: 
# Como el archivo está en 'samples/direct-message-tcp/consumer-topic-tcp.js'
# dentro del contexto de construcción, ahí es donde quedará en el contenedor.
CMD ["node", "consumer-topic-tcp.js"]