# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: span.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# _runtime_version.ValidateProtobufRuntimeVersion(
#     _runtime_version.Domain.PUBLIC,
#     7,
#     35,
#     0,
#     '',
#     'span.proto'
# )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nspan.proto\x12\x1copentelemetry.proto.trace.v1\"`\n\x19\x45xportTraceServiceRequest\x12\x43\n\x0eresource_spans\x18\x01 \x03(\x0b\x32+.opentelemetry.proto.trace.v1.ResourceSpans\"\x88\x01\n\rResourceSpans\x12\x38\n\x08resource\x18\x01 \x01(\x0b\x32&.opentelemetry.proto.trace.v1.Resource\x12=\n\x0bscope_spans\x18\x02 \x03(\x0b\x32(.opentelemetry.proto.trace.v1.ScopeSpans\"F\n\x08Resource\x12:\n\nattributes\x18\x01 \x03(\x0b\x32&.opentelemetry.proto.trace.v1.KeyValue\"?\n\nScopeSpans\x12\x31\n\x05spans\x18\x01 \x03(\x0b\x32\".opentelemetry.proto.trace.v1.Span\"\xa4\x02\n\x04Span\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07span_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04kind\x18\x04 \x01(\x05\x12\x1c\n\x14start_time_unix_nano\x18\x05 \x01(\x04\x12\x1a\n\x12\x65nd_time_unix_nano\x18\x06 \x01(\x04\x12:\n\nattributes\x18\x07 \x03(\x0b\x32&.opentelemetry.proto.trace.v1.KeyValue\x12\x34\n\x06status\x18\x08 \x01(\x0b\x32$.opentelemetry.proto.trace.v1.Status\x12\x31\n\x05links\x18\t \x03(\x0b\x32\".opentelemetry.proto.trace.v1.Link\"N\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.opentelemetry.proto.trace.v1.AnyValue\"n\n\x08\x41nyValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x42\x07\n\x05value\"\x16\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"e\n\x04Link\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07span_id\x18\x02 \x01(\t\x12:\n\nattributes\x18\x03 \x03(\x0b\x32&.opentelemetry.proto.trace.v1.KeyValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'span_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPORTTRACESERVICEREQUEST']._serialized_start=44
  _globals['_EXPORTTRACESERVICEREQUEST']._serialized_end=140
  _globals['_RESOURCESPANS']._serialized_start=143
  _globals['_RESOURCESPANS']._serialized_end=279
  _globals['_RESOURCE']._serialized_start=281
  _globals['_RESOURCE']._serialized_end=351
  _globals['_SCOPESPANS']._serialized_start=353
  _globals['_SCOPESPANS']._serialized_end=416
  _globals['_SPAN']._serialized_start=419
  _globals['_SPAN']._serialized_end=711
  _globals['_KEYVALUE']._serialized_start=713
  _globals['_KEYVALUE']._serialized_end=791
  _globals['_ANYVALUE']._serialized_start=793
  _globals['_ANYVALUE']._serialized_end=903
  _globals['_STATUS']._serialized_start=905
  _globals['_STATUS']._serialized_end=927
  _globals['_LINK']._serialized_start=929
  _globals['_LINK']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
