# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# _runtime_version.ValidateProtobufRuntimeVersion(
#     _runtime_version.Domain.PUBLIC,
#     7,
#     35,
#     0,
#     '',
#     'log.proto'
# )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x1bopentelemetry.proto.logs.v1\"\\\n\x18\x45xportLogsServiceRequest\x12@\n\rresource_logs\x18\x01 \x03(\x0b\x32).opentelemetry.proto.logs.v1.ResourceLogs\"\x83\x01\n\x0cResourceLogs\x12\x37\n\x08resource\x18\x01 \x01(\x0b\x32%.opentelemetry.proto.logs.v1.Resource\x12:\n\nscope_logs\x18\x02 \x03(\x0b\x32&.opentelemetry.proto.logs.v1.ScopeLogs\"E\n\x08Resource\x12\x39\n\nattributes\x18\x01 \x03(\x0b\x32%.opentelemetry.proto.logs.v1.KeyValue\"H\n\tScopeLogs\x12;\n\x0blog_records\x18\x01 \x03(\x0b\x32&.opentelemetry.proto.logs.v1.LogRecord\"\xb6\x01\n\tLogRecord\x12\x16\n\x0etime_unix_nano\x18\x01 \x01(\x04\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\x0f\n\x07span_id\x18\x03 \x01(\t\x12\x33\n\x04\x62ody\x18\x04 \x01(\x0b\x32%.opentelemetry.proto.logs.v1.AnyValue\x12\x39\n\nattributes\x18\x05 \x03(\x0b\x32%.opentelemetry.proto.logs.v1.KeyValue\"M\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.opentelemetry.proto.logs.v1.AnyValue\"n\n\x08\x41nyValue\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x42\x07\n\x05valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPORTLOGSSERVICEREQUEST']._serialized_start=42
  _globals['_EXPORTLOGSSERVICEREQUEST']._serialized_end=134
  _globals['_RESOURCELOGS']._serialized_start=137
  _globals['_RESOURCELOGS']._serialized_end=268
  _globals['_RESOURCE']._serialized_start=270
  _globals['_RESOURCE']._serialized_end=339
  _globals['_SCOPELOGS']._serialized_start=341
  _globals['_SCOPELOGS']._serialized_end=413
  _globals['_LOGRECORD']._serialized_start=416
  _globals['_LOGRECORD']._serialized_end=598
  _globals['_KEYVALUE']._serialized_start=600
  _globals['_KEYVALUE']._serialized_end=677
  _globals['_ANYVALUE']._serialized_start=679
  _globals['_ANYVALUE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
