
apiVersion: v1
kind: Secret
metadata:
  name: confluent-registry
  namespace: confluent
type: kubernetes.io/dockerconfigjson
data:
  # Este es un valor dummy codificado en base64 para {"auths":{}}
  # OK al operador sin necesidad de credenciales reales
  .dockerconfigjson: eyJhdXRocyI6e319
---
apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  dataVolumeCapacity: 10Gi
  storageClass:
    name: hostpath
  image:
    application: docker.io/confluentinc/cp-server:8.1.2
    init: confluentinc/confluent-init-container:3.2.1
  replicas: 1
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:8.1.2
    init: confluentinc/confluent-init-container:3.2.1
  dataVolumeCapacity: 10Gi
  # resources:
  #     requests:
  #       cpu: 1000m
  #       memory: 3Gi
  #     limits:
  #       cpu: 1000m
  #       memory: 3Gi
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  listeners:
      external:
        externalAccess:
          type: nodePort
          nodePort:
            host: localhost
            nodePortOffset: 30000
  # configOverrides:
  #   server:
  #     - advertised.listeners=EXTERNAL://localhost:9092,INTERNAL://kafka.confluent.svc.cluster.local:9071
  #     # IMPORTANTE: Mapear todos los nombres de listener a un protocolo (PLAINTEXT)
  #     - listener.security.protocol.map=EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,REPLICATION:PLAINTEXT,CONTROLLER:PLAINTEXT
  #     - inter.broker.listener.name=INTERNAL
---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server-connect:8.1.2
    init: confluentinc/confluent-init-container:3.2.1
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
---
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-ksqldb-server:8.1.2
    init: confluentinc/confluent-init-container:3.2.1
  dataVolumeCapacity: 10Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-schema-registry:8.1.2
    init: confluentinc/confluent-init-container:3.2.1
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-kafka-rest:8.1.2
    init: confluentinc/confluent-init-container:3.2.1
  # resources:
  #     requests:
  #       cpu: 500m
  #       memory: 1Gi
  #     limits:
  #       cpu: 1000m
  #       memory: 2Gi
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center-next-gen:2.4.1
    init: confluentinc/confluent-init-container:3.2.1
  dataVolumeCapacity: 10Gi
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
    connect:
      - name: connect
        url: http://connect.confluent.svc.cluster.local:8083
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
      - name: ksqldb
        url: http://ksqldb.confluent.svc.cluster.local:8088
  configOverrides:
      server:
        - auto.create.topics.enable=true
        #- confluent.controlcenter.internal.topics.replication=1
        #- confluent.metrics.topic.replication=1
        #- confluent.metrics.topic.min.isr=1
        #- confluent.controlcenter.command.topic.replication=1
        #- confluent.controlcenter.replication.factor=1
        #- confluent.controlcenter.internal.topics.partitions=1
        #- confluent.controlcenter.monitoring.interceptor.topic.partitions=1
        #- confluent.monitoring.interceptor.topic.replication.factor=1
        #- confluent.controlcenter.topic.replication.factor=1
        #- offsets.topic.replication.factor=1
        #- transaction.state.log.replication.factor=1
        #- transaction.state.log.min.isr=1
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-solace-to-kafka
#   namespace: confluent
# spec:
#   podSelector:
#     matchLabels:
#       app: kafka
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: solace
#     ports:
#     - protocol: TCP
#       port: 9071
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: confluent-egress-to-solace
#   namespace: confluent
# spec:
#   podSelector:
#     matchLabels:
#       platform.confluent.io/type: kafka # Ajusta según el label real de tus pods de confluent
#   policyTypes:
#   - Egress
#   egress:
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: solace
#     ports:
#     - protocol: TCP
#       port: 8080    # SEMP (Gestión)
#     - protocol: TCP
#       port: 55555   # SMF (Datos Solace)
#     - protocol: TCP
#       port: 9000    # REST Messaging